nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting_started/index.md
    - Quickstart:
      - getting_started/quickstart/01-overview.md
      - getting_started/quickstart/02-setup.md
      - getting_started/quickstart/03-installation.md
      - getting_started/quickstart/04-configuration.md
      - getting_started/quickstart/05-deployment.md
      - getting_started/quickstart/06-conclusion.md
    - Fundamentals:
      - getting_started/fundamentals/On autonomous Database deployment.md
      - getting_started/fundamentals/About autonomous Model deployment.md
      - getting_started/fundamentals/On scalable Database ecossystem.md
      - getting_started/fundamentals/Understanding complex Model deployment.md
  - Guides:
    - Overview: guides/index.md
    - For Content-Management:
      - RPM Package:
        - new-repo1/docs/content-manager/guides/How to do get light fight..md
      - Debian Package:
        - new-repo2/docs/content-manager/guides/How to bind world none..md
        - new-repo2/docs/content-manager/guides/How to do already choose boy..md
        - new-repo2/docs/content-manager/guides/How to bind since here..md
        - new-repo2/docs/content-manager/guides/How to generate run realize something..md
      - Maven:
        - new-repo3/docs/content-manager/guides/How to generate buy..md
    - For Sys-Admins:
      - RPM Package:
        - new-repo1/docs/sys-admin/guides/How to generate each there..md
        - new-repo1/docs/sys-admin/guides/How to create mention wind..md
      - Debian Package:
        - new-repo2/docs/sys-admin/guides/How to update war..md
        - new-repo2/docs/sys-admin/guides/How to create win crime..md
        - new-repo2/docs/sys-admin/guides/How to update treatment raise collection..md
      - Maven:
        - new-repo3/docs/sys-admin/guides/How to create story wrong newspaper..md
        - new-repo3/docs/sys-admin/guides/How to generate store loss pretty..md
        - new-repo3/docs/sys-admin/guides/How to delete side back create..md
  - Learn:
    - Overview: learn/index.md
    - For Content-Management:
      - RPM Package:
        - 'new-repo1/docs/content-manager/learn/In perspective: resilient Database configuration.md'
        - new-repo1/docs/content-manager/learn/On flexible Artifact ecossystem.md
      - Debian Package:
        - new-repo2/docs/content-manager/learn/Understanding complex Content configuration.md
        - new-repo2/docs/content-manager/learn/On resilient Repository setup.md
        - new-repo2/docs/content-manager/learn/About scalable Model deployment.md
      - Maven:
        - new-repo3/docs/content-manager/learn/About autonomous Repository configuration.md
        - 'new-repo3/docs/content-manager/learn/In perspective: flexible Repository
          setup.md'
        - 'new-repo3/docs/content-manager/learn/In perspective: modular Repository configuration.md'
    - For Sys-Admins:
      - RPM Package:
        - new-repo1/docs/sys-admin/learn/Understanding autonomous Model deployment.md
        - new-repo1/docs/sys-admin/learn/On resilient Content configuration.md
        - new-repo1/docs/sys-admin/learn/Understanding flexible Model ecossystem.md
      - Debian Package:
        - new-repo2/docs/sys-admin/learn/On modular Model setup.md
      - Maven:
        - new-repo3/docs/sys-admin/learn/On scalable Database configuration.md
        - 'new-repo3/docs/sys-admin/learn/In perspective: complex Database deployment.md'
        - new-repo3/docs/sys-admin/learn/Understanding modular Content setup.md
  - Reference:
    - Overview: reference/index.md
    - Repository Map: reference/01-repository-map.md
    - Glossary: reference/02-glossary.md
    - Repositories:
      - RPM Package:
        - '&#128279; Rest API': https://docs.pulpproject.org/pulp_rpm/restapi.html
        - Code API:
          - new-repo1/docs/reference/main.md
          - Models:
            - new-repo1/docs/reference/models/repository.md
            - new-repo1/docs/reference/models/remotes.md
            - new-repo1/docs/reference/models/artifacts.md
        - Changelog: new-repo1/CHANGELOG.md
      - Debian Package:
        - '&#128279; Rest API': https://docs.pulpproject.org/pulp_deb/restapi.html
        - Code API:
          - new-repo2/docs/reference/main.md
        - Changelog: new-repo2/CHANGELOG.md
      - Maven:
        - '&#128279; Rest API': https://docs.pulpproject.org/pulp_maven/restapi.html
        - Code API:
          - new-repo3/docs/reference/main.md
        - Changelog: new-repo3/CHANGELOG.md
  - Development:
    - Overview: development/index.md
    - Quickstart:
      - development/quickstart/01-doc-workflow.md
      - development/quickstart/02-code-workflow.md
    - Onboarding:
      - development/onboarding/On autonomous Database deployment.md
      - development/onboarding/About autonomous Model deployment.md
      - development/onboarding/On scalable Database ecossystem.md
      - development/onboarding/Understanding complex Model deployment.md
    - Guides:
      - development/guides/How to bind analysis trade..md
        


site_name: Pulp Project
site_url: https://github.com/pulp/pulpcore
repo_url: https://github.com/pulp/pulpcore
repo_name: pulp/pulpcore
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  features:
#    - navigation.footer # customize this color later
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
#    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
#      toggle:
#        icon: material/toggle-switch-off-outline 
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate 
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode    

plugins:
  - search
  - tags:
      tags_file: tags.md
  - mkdocstrings:
      handlers: 
        python:
          options:
            show_source: false
            docstring_section_style: table # table, list, spacy
          paths:
            - temp_dir/new-repo1
            - temp_dir/new-repo2
            - temp_dir/new-repo3

  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - import_url: file:///home/pbrochad/workspace/multirepo-prototype/new_repo1?branch=main
          imports:
          - docs/*
          - new_repo1
          - CHANGELOG.md
          name: new_repo1
        - import_url: file:///home/pbrochad/workspace/multirepo-prototype/new_repo2?branch=main
          imports:
          - docs/*
          - new_repo2
          - CHANGELOG.md
          name: new_repo2
        - import_url: file:///home/pbrochad/workspace/multirepo-prototype/new_repo3?branch=main
          imports:
          - docs/*
          - new_repo3
          - CHANGELOG.md
          name: new_repo3


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pulp
    - icon: fontawesome/brands/discourse
      link: https://discourse.pulpproject.org/

extra_css:
  - css/extra.css
  - css/mkdocstrings.css

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

      # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: |
  &copy; 2023 <a href="https://github.com/pulp"  target="_blank" rel="noopener">Pulp Project</a>