[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pulp-docs"
version = "0.0.1"
dependencies = [
    "mkdocs-material",
    "mkdocs-material[imaging]",
    "mkdocstrings[python]",
    "mkdocs-macros-plugin",
    "Jinja2",
    "Faker",
]

[project.scripts]
pulp-docs = "pulp_docs.main:main"

[tool.setuptools.packages.find]
where = ["src"]


