site_name: Pulp Project
site_url: https://staging-docs.pulpproject.org/
repo_url: https://github.com/pulp/pulpcore
repo_name: pulp/pulpcore

docs_dir: docs
theme:
  name: material
  logo: pulp-docs/assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    

plugins:
  - search
  - macros:
      module_name: 'mkdocs_macros'
  - tags:
      tags_file: pulp-docs/tags.md
  - mkdocstrings:
      handlers: 
        python:
          options:
            show_source: false
            docstring_section_style: table # table, list, spacy

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/pulp
    - icon: fontawesome/brands/discourse
      link: https://discourse.pulpproject.org/

extra_css:
  - pulp-docs/css/extra.css
  - pulp-docs/css/mkdocstrings.css

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: |
  &copy; 2023 <a href="https://github.com/pulp"  target="_blank" rel="noopener">Pulp Project</a>
