# workflow from: https://squidfunk.github.io/mkdocs-material/publishing-your-site/

name: ci 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name:
        run: |
          pip install build
          python -m build
          pip install dist/*.whl
          pulp-docs build
          tree site
